import altitude_training_webp from '../public/image/article/altitude-training.webp'
import { type feature_T } from './_subtle.js'
export const altitude_training = <feature_T>{
	title: 'Altitude Training',
	description: `Altitude training enhances some endurance athletes' performance by increasing their oxygen-carrying capacity through living high and training low.`,
	slug: 'altitude-training',
	tag_a1: [
		'altitude',
		'altitude-athletic',
		'altitude-running',
		'altitude-training',
		'altitude-training-chamber',
		'altitudemask',
		'altitudes-gym',
		'athletic',
		'atitude-training',
		'elevation-training',
		'endurance',
		'endurance-athletes',
		'erythropoietin-epo',
		'ewot',
		'exercise',
		'hematocrit-increase',
		'high-altitude-running',
		'high-atitude-training',
		'high-elevation-running',
		'high-elevation-training',
		'hypoxic-training',
		'hypoxic-training',
		'individual-response-to-hypoxia',
		'iron-stores-and-nutrition',
		'limitations-of-high-altitude-training',
		'live-high-train-low',
		'non-surgical',
		'oxygen',
		'oxygen-capacity',
		'training',
	],
	hero_image: altitude_training_webp,
}
