import { type feature_T, placeholder_hero_image } from './_subtle.js'
export const blood_flow_analysis = <feature_T>{
	title: 'Blood Flow Analysis',
	slug: 'blood-flow-analysis',
	// language=md
	description: `
Our cardiovascular system is a marvel of nature. Responsible for delivering oxygen and vital nutrients to every corner of our body. When blood flow is compromised, the consequences can be far-reaching. Blood flow analysis offers powerful tools to:

- assess vascular health
- detect diseases like atherosclerosis
- guide preventive or therapeutic interventions`.trim(),
	tag_a1: [
		'a-fib-heart',
		'a-fib-symptoms',
		'a-heart',
		'ablation-for-atrial-fibrillation',
		'ablations',
		'about-heart',
		'afib-diet',
		'afib-heart',
		'afib-heart-condition',
		'afib-symptoms',
		'afib-symptoms-and-signs',
		'aha-blood-pressure-guidelines',
		'aha-diet',
		'aha-heart',
		'american-heart-association-blood-pressure',
		'american-heart-association-diet',
		'analyze-my-blood-pressure',
		'aortic-disease',
		'aortic-stenosis-treatment',
		'aortic-valve-disease',
		'aortic-valve-stenosis-symptoms',
		'arrhythmia-dietary-supplement',
		'arrhythmia-symptoms',
		'arterial-pressure-waveform-analysis',
		'arteriosclerotic-cardiovascular-disease',
		'artery-cleansing-drink',
		'artery-disease',
		'atherosclerotic-heart-disease',
		'atrial-fibrillation-nhs',
		'atrial-fibrillation-symptoms',
		'attack-symptoms',
		'average-artery-blockage-by-age',
		'best-cooking-oil-for-high-cholesterol',
		'best-diet-for-heart-disease-reversal',
		'best-diet-for-heart-health',
		'best-food-for-heart',
		'best-foods-for-heart-health',
		'best-foods-for-your-heart-and-arteries',
		'best-foods-you-can-eat-to-reduce-cholesterol',
		'best-heart-healthy-diet',
		'best-heart-healthy-foods',
		'best-supplements-for-heart-health',
		'best-vitamins-for-heart-and-circulation',
		'bicuspid-aortic-valve-symptoms',
		'blockage-in-heart',
		'blocked-artery-in-heart',
		'blood-analysis',
		'blood-cholesterol',
		'blood-circulation-in-heart',
		'blood-circulation-in-heart-steps',
		'blood-flow',
		'blood-flow-analysis',
		'blood-pressure-analysis',
		'blood-pressure-analyzer',
		'blood-pressure-reading-analysis',
		'blood-pressure-test',
		'blood-pressure-waveform-analysis',
		'blood-test-bp',
		'blood-test-for-bp',
		'bp-analysis',
		'bp-results-analysis',
		'brain-and-heart',
		'cabbage-heart-surgery',
		'calcium-heart-scan',
		'calcium-in-heart',
		'cardiac-arrhythmia-symptoms',
		'cardiac-attack',
		'cardiac-catheterization',
		'cardiac-chest-pain',
		'cardiac-clinic',
		'cardiac-diet',
		'cardiac-diet-plan',
		'cardiac-disease',
		'cardiac-disorders',
		'cardiac-health',
		'cardiac-rehabilitation',
		'cardiac-symptoms',
		'cardiac-therapy',
		'cardio-clinic',
		'cardio-health',
		'cardiologist-specialist',
		'cardiology-clinic',
		'cardiovascular-disease',
		'cardiovascular-disease-prevention',
		'cardiovascular-disease-risk-factors',
		'cardiovascular-disease-symptoms',
		'cardiovascular-diseases-list',
		'cardiovascular-disorders',
		'cardiovascular-health',
		'cardiovascular-health-clinic',
		'cardiovascular-problems',
		'cardiovascular-risk-factors',
		'cardiovascular-symptoms',
		'causes-of-aortic-stenosis',
		'causes-of-cardiovascular-disease',
		'causes-of-chest-pain-in-women',
		'causes-of-congestive-heart-failure',
		'causes-of-heart-failure',
		'chest-pain',
		'chest-pain-1-year-after-bypass-surgery',
		'chest-pain-after-running',
		'chest-pain-and-high-blood-pressure',
		'chest-pain-and-left-arm-pain',
		'chest-pain-causes',
		'chest-pain-causes-and-treatment',
		'chest-pain-causes-in-females',
		'chest-pain-for-a-week',
		'chest-pain-for-days',
		'chest-pain-from-stress-for-days',
		'chest-pain-in-women',
		'chest-pain-management',
		'chest-pain-near-heart',
		'chest-pain-remedies',
		'chest-pain-treatments',
		'cholesterol-and-heart-disease',
		'cholesterol-diet',
		'cholesterol-level',
		'cholesterol-plaque',
		'cholesterol-treatment',
		'chronic-chest-pain',
		'chronic-congestive-heart-failure',
		'chronic-heart-failure',
		'chronic-heart-failure-symptoms',
		'circulation-heart-failure',
		'circulation-of-heart',
		'circulatory-disease',
		'common-causes-of-chest-pain',
		'common-heart-diseases',
		'common-heart-problems',
		'community-heart-and-vascular',
		'congenital-heart',
		'congenital-heart-defects',
		'congenital-heart-disease',
		'congenital-heart-disease-causes',
		'congenital-heart-disease-symptoms',
		'congenital-heart-disease-treatment',
		'congestive-heart',
		'congestive-heart-disease',
		'congestive-heart-failure',
		'congestive-heart-failure-diet',
		'congestive-heart-failure-symptoms',
		'congestive-heart-failure-treatment',
		'copd-and-heart-failure',
		'coronary-arteries-of-the-heart',
		'coronary-artery-bypass',
		'coronary-artery-disease',
		'coronary-artery-disease-prevention',
		'coronary-artery-disease-risk-factors',
		'coronary-artery-disease-surgery',
		'coronary-artery-disease-symptoms',
		'coronary-artery-disease-treatments',
		'coronary-bypass-surgery',
		'coronary-catheterization',
		'coronary-disease',
		'coronary-heart-disease',
		'coronary-heart-disease-causes',
		'coronary-heart-disease-risk-factors',
		'coronary-heart-disease-symptoms',
		'coronary-heart-disease-treatment',
		'cure-for-heart-disease',
		'cva-heart',
		'cvd-disease',
		'cvd-risk-factors',
		'cyanotic-heart-disease',
		'damar-hamlin-heart-condition',
		'detox-foot-patch',
		'diastolic-heart-failure',
		'diastolic-heart-failure-symptoms',
		'diet-after-heart-valve-replacement',
		'diet-for-heart-disease',
		'diet-for-high-cholesterol',
		'doppler-blood-flow-analysis',
		'early-signs-of-heart-disease',
		'early-signs-of-heart-failure',
		'early-symptoms-of-heart-failure',
		'electrophysiology-cardiologist',
		'enlarged-heart',
		'enlarged-heart-causes',
		'enlarged-heart-nhs',
		'enlarged-heart-symptoms',
		'enlarged-heart-treatment',
		'enlarged-heart-treatment-diet',
		'facts-about-the-heart',
		'female-chest-pain-causes',
		'first-heart-transplant',
		'food-for-heart-failure',
		'food-for-the-heart',
		'food-good-for-heart',
		'foods-that-are-good-for-your-heart',
		'foods-that-prevent-heart-disease',
		'genetic-heart-conditions',
		'good-cholesterol-levels',
		'good-food-for-cholesterol',
		'hdl-good-cholesterol',
		'healthy-cholesterol',
		'healthy-cholesterol-level',
		'healthy-ldl-levels',
		'heart-ablation',
		'heart-ablation-for-afib',
		'heart-ablation-surgery',
		'heart-age',
		'heart-and-family-health-institute',
		'heart-and-stroke',
		'heart-and-vascular',
		'heart-arrhythmia',
		'heart-arrhythmia-causes',
		'heart-arrhythmia-symptoms',
		'heart-arrhythmia-treatments',
		'heart-arrhythmia-types',
		'heart-arteries',
		'heart-attacks',
		'heart-attacks-in-women',
		'heart-awareness-month',
		'heart-balloon-surgery',
		'heart-blockage-symptoms',
		'heart-blockage-treatment',
		'heart-blockage-treatment-without-surgery',
		'heart-blood',
		'heart-bypass',
		'heart-bypass-surgery',
		'heart-care',
		'heart-catheterization',
		'heart-check',
		'heart-check-up',
		'heart-condition-symptoms',
		'heart-conditions',
		'heart-conditions-list',
		'heart-defects',
		'heart-defibrillator',
		'heart-diet',
		'heart-diet-plan',
		'heart-disease-and-stroke',
		'heart-disease-awareness-month',
		'heart-disease-facts',
		'heart-disease-in-women',
		'heart-disease-prevention',
		'heart-disease-risk-factors',
		'heart-disease-symptoms',
		'heart-disease-symptoms-in-men',
		'heart-diseases-list',
		'heart-disorders',
		'heart-doctor',
		'heart-failure',
		'heart-failure-clinic',
		'heart-failure-diet',
		'heart-failure-management',
		'heart-failure-prognosis',
		'heart-failure-self-care',
		'heart-failure-surgery',
		'heart-failure-symptoms',
		'heart-failure-symptoms-in-women',
		'heart-failure-treatment-in-elderly',
		'heart-failure-treatments',
		'heart-flow-analysis',
		'heart-friendly-foods',
		'heart-group',
		'heart-health',
		'heart-health-check',
		'heart-health-check-up',
		'heart-health-month',
		'heart-health-supplements',
		'heart-healthy-diet',
		'heart-healthy-diet-foods',
		'heart-healthy-diet-plan',
		'heart-healthy-dinners',
		'heart-healthy-foods',
		'heart-healthy-foods-list',
		'heart-healthy-lifestyle',
		'heart-healthy-meal-plans',
		'heart-healthy-meals',
		'heart-healthy-snacks',
		'heart-institute',
		'heart-issues',
		'heart-issues-in-women',
		'heart-issues-symptoms',
		'heart-keep',
		'heart-medical',
		'heart-mri',
		'heart-mri-scan',
		'heart-org',
		'heart-pain',
		'heart-pain-after-eating',
		'heart-pain-causes',
		'heart-pain-in-women',
		'heart-pain-symptoms',
		'heart-plaque',
		'heart-pressure',
		'heart-problems',
		'heart-problems-in-women',
		'heart-problems-symptoms',
		'heart-scan',
		'heart-screening',
		'heart-smart',
		'heart-specialist',
		'heart-specialist-doctor',
		'heart-stress-symptoms',
		'heart-stroke',
		'heart-stroke-causes',
		'heart-stroke-symptoms',
		'heart-supplements',
		'heart-surgery',
		'heart-surgery-types',
		'heart-symptoms',
		'heart-symptoms-in-women',
		'heart-treatment',
		'heart-valve-disease-symptoms',
		'heart-valve-disease-treatment-without-surgery',
		'heart-valve-problems',
		'heart-valve-replacement',
		'heart-valve-replacement-surgery',
		'heart-valve-specialist',
		'heart-valve-symptoms',
		'heart-valves',
		'heart-vitamins',
		'heart-weight',
		'heart-without-blood',
		'heartflow-analysis-cost',
		'hearts-main-artery',
		'herbs-for-heart-health',
		'hereditary-heart-conditions',
		'hereditary-heart-disease',
		'high-blood-cholesterol',
		'high-cholesterol',
		'high-cholesterol-levels',
		'high-fat-diet',
		'high-ldl-cholesterol-causes',
		'home-remedies-for-chest-pain',
		'home-remedies-for-heart-valve-problems',
		'hypertensive-heart-disease-with-heart-failure',
		'hypoplastic-left-heart',
		'ideal-cholesterol-levels',
		'improve-heart-health',
		'in-heart',
		'indigestion-and-chest-pain',
		'indigestion-pain-in-chest',
		'indigestion-symptoms-chest',
		'information-about-heart',
		'interventional-cardiologist',
		'irregular-blood-pressure',
		'ischemic-heart-disease',
		'ischemic-heart-disease-causes',
		'ischemic-heart-disease-symptoms',
		'ldl-and-hdl-levels',
		'ldl-cholesterol-high',
		'leaking-heart-valve-prognosis-in-elderly',
		'leaking-heart-valve-symptoms',
		'leaky-heart-valve',
		'leaky-heart-valve-surgery',
		'leaky-heart-valve-treatment',
		'leaky-mitral-valve',
		'left-arm-and-chest-pain',
		'left-chest-pain',
		'left-chest-pain-after-eating',
		'left-chest-pain-causes',
		'left-heart-catheterization',
		'left-heart-failure-symptoms',
		'left-sided-chest-pain',
		'left-sided-heart-failure',
		'living-with-heart-failure',
		'low-good-cholesterol',
		'lower-chest-pain',
		'lower-left-chest-pain',
		'lowering-cholesterol',
		'mild-chest-pain',
		'mitral-stenosis-symptoms',
		'mitral-valve-disease',
		'mitral-valve-replacement-surgery',
		'mitral-valve-symptoms',
		'most-common-congenital-heart-disease',
		'most-common-heart-disease',
		'myocardial-disease',
		'myocardial-infarction-risk-factors',
		'myocardial-infarction-symptoms',
		'neck-and-chest-pain',
		'non-surgical',
		'normal-heart-weight',
		'open-heart-bypass-surgery',
		'oracle-heart-and-vascular',
		'pain-in-my-heart',
		'pain-near-heart',
		'pressure-blood-test',
		'prevent-and-reverse-heart-disease',
		'pulmonary-heart-disease',
		'pulmonary-stenosis-symptoms',
		'reverse-heart-disease',
		'rheumatic-heart',
		'rheumatic-heart-disease',
		'rheumatic-heart-disease-causes',
		'rheumatic-heart-disease-symptoms',
		'right-chest-pain-causes',
		'right-sided-heart-failure-symptoms',
		'risk-factors-for-heart-failure',
		'sands-constellation-heart-institute',
		'severe-heart-failure',
		'signs-and-symptoms-of-cardiovascular-disease',
		'signs-and-symptoms-of-congestive-heart-failure',
		'signs-and-symptoms-of-heart-failure',
		'signs-and-symptoms-of-myocardial-infarction',
		'signs-of-a-healthy-heart',
		'signs-of-a-weak-heart',
		'signs-of-cardiovascular-disease',
		'signs-of-congestive-heart-failure',
		'signs-of-enlarged-heart',
		'signs-of-heart-blockage',
		'signs-of-heart-disease-in-men',
		'signs-of-heart-disease-in-women',
		'signs-of-heart-failure',
		'signs-of-heart-failure-in-women',
		'signs-of-heart-issues',
		'signs-of-heart-issues-in-women',
		'signs-of-heart-problems',
		'signs-of-heart-problems-in-women',
		'signs-of-heart-trouble',
		'signs-of-heart-valve-problems',
		'smoking-and-cholesterol',
		'statins-for-cholesterol',
		'stenosis-heart',
		'stress-and-chest-pain',
		'stress-and-heart-disease',
		'stress-chest-pain',
		'symptoms-of-a-fib',
		'symptoms-of-afib-in-women',
		'symptoms-of-blocked-arteries',
		'symptoms-of-chest-pain',
		'symptoms-of-clogged-arteries',
		'symptoms-of-heart-disease-in-women',
		'symptoms-of-heart-failure-after-bypass-surgery',
		'symptoms-of-heart-problems-in-women',
		'symptoms-of-heart-valve-problems',
		'systolic-blood-pressure',
		'systolic-heart-failure',
		'tavr',
		'tavr-surgery',
		'tavr-valve',
		'test-your-blood-pressure',
		'the-american-heart-association',
		'the-cholesterol-myth',
		'the-great-cholesterol-myth',
		'treatment-for-a-fib',
		'treatment-for-breathlessness-in-heart-failure',
		'treatment-for-high-cholesterol',
		'triple-bypass-heart-surgery',
		'triple-bypass-surgery',
		'triple-heart-bypass',
		'types-of-cardiovascular-disease',
		'types-of-chest-pain',
		'types-of-congenital-heart-disease',
		'types-of-heart',
		'types-of-heart-attacks',
		'types-of-heart-failure',
		'types-of-heart-monitors',
		'types-of-heart-problems',
		'types-of-heart-scan',
		'types-of-heart-valve-replacement',
		'types-of-ischemic-heart-disease',
		'types-of-open-heart-surgery',
		'valve-disease',
		'valvular-heart-disease-symptoms',
		'vascular-institute',
		'vegetables-good-for-the-heart',
		'vitamins-for-heart-health',
		'vitamins-to-strengthen-heart',
		'ways-to-prevent-heart-disease',
		'weak-heart',
		'weak-heart-symptoms',
		'weak-heart-treatment',
		// '10-ways-to-keep-your-heart-healthy',
		// '25-heart-healthy-foods',
		// '3-best-herbs-for-heart-health',
		// '4-valves-of-the-heart',
		// 'acc-aha-guidelines',
		// 'ace-heart-clinic',
		// 'aha-hypertension-guidelines',
		// 'aha-stroke-guidelines',
		// 'american-heart-association-2022',
		// 'american-heart-month',
		// 'baptist-cardiology',
		// 'best-cardiologist-near-me',
		// 'bryan-heart',
		// 'cardiologist-clinic-near-me',
		// 'cardiologist-near-me',
		// 'february-heart-month',
		// 'female-cardiologist-near-me',
		// 'heart-check-up-near-me',
		// 'heart-day-2022',
		// 'heart-doctor-near-me',
		// 'heart-implant',
		// 'heart-month',
		// 'heart-month-2022',
		// 'heart-scan-near-me',
		// 'heart-specialist-doctor-near-me',
		// 'heart-specialist-near-me',
		// 'heart-stroke-in-spanish',
		// 'heart-transplant',
		// 'heart-transplant-cost',
		// 'heart-transplant-surgery',
		// 'laser-speckle-contrast-analysis',
		// 'million-hearts',
		// 'one-heart-care',
		// 'pacemakers-of-the-heart',
		// 'pediatric-cardiologist-near-me',
		// 'people-heart',
		// 'prairie-heart-institute',
		// 'susan-lucci-heart-surgery',
		// 'the-heart-group',
		// 'the-heart-institute',
		// 'top-10-cardiologist-near-me',
		// 'top-cardiologist-near-me',
		// 'unc-cardiology',
	],
	hero_image: placeholder_hero_image,
}
