import { type feature_T, placeholder_hero_image } from './_subtle.js'
export const comprehensive_wellness_testing_and_biometric_screening_for_companies = <feature_T>{
	title: 'Comprehensive Wellness Testing & Biometric Screening for Companies',
	description: `Comprehensive wellness testing and biometric screening stand are pillars of proactive health management. This diagnostic duo offers a deep dive into the intricacies of your health. Providing actionable insights that pave the way for personalized health strategies.`,
	slug: 'comprehensive-wellness-testing-and-biometric-screening-for-companies',
	tag_a1: [
		'biometric-health-screening',
		'biometric-screening',
		'biometric-testing',
		'biometric-wellness-screening',
		'comprehensive-wellness-testing',
		'comprehensive-wellness-testing-and-biometric-screening',
		'health-check',
		'health-screening',
		'health-test',
		'non-surgical',
		'quest-diagnostic-wellness-screening',
		'screening',
		'testing',
		'wellness-blood-screening',
		'wellness-blood-test',
		'wellness-checkup',
		'wellness-screening',
		'wellness-testing',
		'women-health-check',
		'women-health-exams',
		'yearly-checkup',
		'yearly-checkup-for-women',
	],
	hero_image: placeholder_hero_image,
}
