import { lines_ } from '@rappstack/ui--any/string'
import hero_image from '../public/image/article/detox-therapy.webp'
import { type feature_T } from './_subtle.js'
export const detox_therapy = <feature_T>{
	title: `Detox Therapy`,
	description: `Detox therapy is a critical first step in the journey to recovery from substance abuse & addiction. It involves the process of eliminating toxins from the body, managing withdrawal symptoms, & preparing individuals for ongoing treatment.`,
	description_md: lines_(
		`Detox therapy is a critical first step in the journey to recovery from substance abuse & addiction. It involves the process of:`,
		`- eliminating toxins from the body`,
		`- managing withdrawal symptoms`,
		`- preparing individuals for ongoing treatment`,),
	slug: 'detox-therapy',
	tags: [
		'addiction-rehab',
		'alcohol-detox',
		'alcohol-rehab',
		'alcohol-treatment-centers',
		'detox',
		'detox-center',
		'detox-facilities',
		'detox-for-alcoholics',
		'detox-programs',
		'detox-therapy',
		'drug-and-alcohol-rehab',
		'drug-detox',
		'drug-rehab',
		'enhanced-physical-performance',
		'inpatient-rehab',
		'medical-detox',
		'non-surgical',
		'outpatient-drug-rehab',
		'outpatient-rehab',
		'rehab',
		'rehab-alcohol',
		'rehab-center',
		'rehab-drug',
		'rehab-for-drinking',
		'rehab-for-drugs',
		'rehab-treatment-center',
		'substance-abuse-rehab-centers',
		'therapy',
		'well-being',
	],
	hero_image,
}
