import hero_image from '../public/image/article/epidural-neoregeneration.webp'
import { type feature_T, placeholder_hero_image } from './_subtle.js'
export const epidural_neoregeneration = <feature_T>{
	title: 'Epidural Neoregeneration',
	slug: 'epidural-neoregeneration',
	description: `Epidural Neuroregeneration is a frontier in pain management and spinal health. It's about healing nerve damage. This method employs the epidural space near the spine. The goal? To foster nerve repair and reduce pain.`,
	tag_a1: [
		'anti-aging',
		'back-injury',
		'back-pain',
		'back-pain-in-middle-of-back',
		'back-pain-low',
		'back-pain-relief',
		'back-pains',
		'epidural',
		'epidural-neoregeneration',
		'low-back-pain',
		'low-right-back-pain',
		'lower-back-pain-therapies',
		'lower-back-pain-treatment',
		'lower-left-back-pain',
		'neck-pain-back-pain',
		'neoregeneration',
		'nerve-damage',
		'non-surgical',
		'sharp-back-pain',
		'spine-and-back-pain',
		'spine-back-pain',
		'spine-health',
		'spine-surgeons',
	],
	hero_image,
}
