import { type feature_T, placeholder_hero_image } from './_subtle.js'
export const eureka_diagnostics_reference_lab = <feature_T>{
	title: 'Eureka Diagnostics Reference Lab',
	slug: 'eureka-diagnostics-reference-lab',
	// language=md
	description: `Eureka Diagnostics provides precise, reliable, and rapid diagnostic services. Eureka Diagnostics leverages the latest in medical technology to deliver comprehensive testing solutions.`.trim(),
	tag_a1: [
		'blood-diagnostics',
		'blood-panel',
		'blood-test',
		'blood-testing-lab',
		'bloodwork',
		'breast-diagnostic',
		'breast-diagnostic-center',
		'clinical-diagnostic-center',
		'clinical-diagnostic-centre',
		'diagnostic-blood-tests',
		'diagnostic-cardiology',
		'diagnostic-center',
		'diagnostic-center-for-women',
		'diagnostic-centre',
		'diagnostic-clinic',
		'diagnostic-imaging-center',
		'diagnostic-laboratory-services',
		'diagnostics',
		'diagnostics-center',
		'diagnostics-lab',
		'diagnostics-laboratory',
		'dna-diagnostics-center',
		'dna-test-lab',
		'dna-testing',
		'dna-testing-center',
		'eureka-diagnostics',
		'eureka-diagnostics-reference-lab',
		'fetal-diagnostic-center',
		'health-diagnostics',
		'hi-tech-lab',
		'lab',
		'laboratory-blood-test',
		'labs-for-kidney-function',
		'male-hormone-panel-blood-test',
		'medical-diagnostic-imaging',
		'medical-diagnostic-lab',
		'medical-diagnostic-laboratory',
		'medical-testing-lab',
		'molecular-diagnostics-laboratory',
		'molecular-test',
		'mri-center',
		'mri-diagnostic-centre',
		'non-surgical',
		'outpatient-mri',
		'paternity-test',
		'preventative-diagnostic-center',
		'radiology',
		'radiology-lab',
		'regional-imaging',
		'reference-lab',
		'test-lab',
		'testing',
		'vascular-lab',
		'walkin-lab',
	],
	hero_image: placeholder_hero_image,
}
