import { type feature_T, placeholder_hero_image } from './_subtle.js'
export const exercise_with_oxygen_therapy = <feature_T>{
	title: `Exercise with Oxygen Therapy (EWOT)`,
	slug: 'exercise-with-oxygen-therapy-ewot',
	description: `Supercharge your exercise routine & boost your overall well-being. Exercise with Oxygen Therapy (EWOT). Dr. Manny Emenike, a renowned Internal Medicine specialist & former endurance athlete. Will guide you.`,
	tag_a1: [
		'exercise',
		'oxygen',
		'ewot',
		'exercise-with-oxygen-therapy',
		'therapy',
		'oxygen-therapy',
		'stamina',
		'accelerated-recovery',
		'cardiovascular-health',
		'detoxification',
		'mental-clarity',
		'inflammation-reduction',
		'weight-loss',
		'enhanced-physical-performance',
		'non-surgical',
	],
	// hero_image: exercise_with_oxygen_therapy_webp,
	hero_image: placeholder_hero_image,
}
